Settings As screen:
    Fill: =If(DarkMode, Color.Black, Color.White)

    Rectangle2_3 As rectangle:
        BorderColor: =RGBA(56, 96, 178, 1)
        Fill: =RGBA(0, 134, 208, 1)
        Height: =104
        Width: =640
        ZIndex: =1

    Image6_16 As image:
        Height: =74
        Image: ='Microsoft logo'
        Width: =133
        X: =507
        Y: =19
        ZIndex: =2

    Label6_23 As label:
        Align: =Align.Right
        Color: =RGBA(255, 255, 255, 1)
        Font: =Font.'Segoe UI'
        FontWeight: =FontWeight.Semibold
        Height: =54
        Size: =32
        Text: ="Settings"
        Width: =198
        X: =207
        Y: =25
        ZIndex: =3

    Label4_3 As label:
        Color: =If(DarkMode, Color.White, Color.Black)
        Height: =206
        Size: =20
        Text: ="Email me when a new roadmap item is added"
        Width: =319
        X: =67
        Y: =338
        ZIndex: =4

    HtmlText1_3 As htmlViewer:
        Color: =If(DarkMode, Color.White, Color.Black)
        DisabledBorderColor: =RGBA(56, 56, 56, 1)
        Height: =102
        HtmlText: ="<i>The Microsoft 365 roadmap provides estimated release dates and descriptions for commercial features. All information is subject to change.</i>"
        Size: =14
        Width: =548
        X: =62
        Y: =1012
        ZIndex: =5

    Image6_17 As image:
        Height: =270
        Image: ='Microsoft logo'
        Width: =509
        X: =62
        Y: =131
        ZIndex: =6

    Icon2_14 As icon.ChevronLeft:
        Height: =35
        Icon: =Icon.ChevronLeft
        OnSelect: =Navigate('Roadmap startpage')
        Width: =42
        X: =25
        Y: =38
        ZIndex: =7

    Toggle1 As toggleSwitch:
        Height: =49
        OnCheck: =ClickabuttoninPowerAppstosendanemail.Run(User().Email, "New roadmap item added", "New roadmap item added")
        ShowLabel: =false
        Size: =21
        Width: =154
        X: =456
        Y: =417
        ZIndex: =8

    Label4_4 As label:
        Color: =If(DarkMode, Color.White, Color.Black)
        Height: =206
        Size: =20
        Text: ="Dark mode"
        Width: =319
        X: =62
        Y: =439
        ZIndex: =9

    Toggle1_1 As toggleSwitch:
        Height: =49
        OnCheck: =Set(DarkMode, true)
        OnUncheck: =Set(DarkMode, false)
        ShowLabel: =false
        Size: =21
        Width: =154
        X: =456
        Y: =518
        ZIndex: =10

